### PR TITLE
feat(sim): started developing simulation for robot

### PR DESCRIPTION
**Pull request by DaPortlyJester**
Added physics.py to configure simullated components of the robot.

Added defaulted arguments to `RobotController` class to support simulation environment configuration. Arguments include paths for files for:
- subsystems.ini
- joysticks.ini
- autonomous.ini

Some cleanup and test fixes.

### CODE REVIEW

**Comment by DaPortlyJester** [comment]
Needs rebase

**Comment by DaPortlyJester** [comment]
THis is not ready for merge, and needs more work to make the simulation function.

**Comment by DaPortlyJester** [comment]
> THis is not ready for merge, and needs more work to make the simulation function.

Also an opportunity to work on CI / github actions.

**Review by Dunkle-Stiltskin — APPROVED** [review]
I see nothing I don't agree with.  The few confusions I figured out (and were from my own lack of understanding).

**Review by dr-edmond-merkle — APPROVED** [review]
LGTM

**Pull request merged**
